# ESLint
#
#   Configuration: http://eslint.org/docs/user-guide/configuring
#   Rules: http://eslint.org/docs/rules/

---
  env:
    node: true
  extends:
   - eslint:recommended
   - plugin:@typescript-eslint/recommended
   - prettier

  globals:
    Promise: true
